version: "3.8"
services:
  gitrepo:
    build: gitrepo
    ports:
       - "#{gitea.host.port}:3000"

  builder:
    build: builder
    ports:
       - "#{builder.host.port}:5555"
       - "#{builder.host.diagnostics.port}:9999"
       - "#{builder.host.um.port}:9001"
